Update Task1
OlesOv/altexsoft-lab-2020 pull request #2
Opened 2020-08-21 02:03 UTC by OlesOv

Added .gitignore, file existing check, FIleSystemInfo's sort and regexps. Changed to .NetCore

2020-08-25 16:48 UTC, alex-geraschenko requested changes
1. Разнесите методы задач по разным классам в соответствии с принципами SOLID. Понадобится наследование
2. Классы принято называть существительными, методы - глаголами
3. Проследите, чтобы не было дублирования кода. Принцип DRY

2020-08-25 16:48 UTC, alex-geraschenko commented on Task1/Task1/Program.cs
> +            if (!File.Exists(@originalPath))
Символ `@` используется для экранирования переменной, если она навана одним из ключевых слов. Например `@value`. В остальных случаях использовать его в имени переменной нет смысла

2020-08-31 11:01 UTC, alex-geraschenko requested changes
1. Разнесите классы по разным файлам: 1 класс - 1 файл.
2. Почему все классы абстрактные ?

2020-08-31 11:58 UTC, OlesOv commented
> 1. Разнесите классы по разным файлам: 1 класс - 1 файл.
Ок.

> 2. Почему все классы абстрактные ?
Чтоб не было возможно создать экземпляр класса, ведь в этом нет необходимости.

2020-08-31 12:22 UTC, alex-geraschenko commented
> Чтоб не было возможно создать экземпляр класса, ведь в этом нет необходимости.

Это неправильно. Либо делайте их статическими, но тогда не будет возможности наследоваться, либо создавайте экземпляры. И только базовый класс должен быть абстрактным

2020-08-31 12:25 UTC, alex-geraschenko requested changes

2020-08-31 12:25 UTC, alex-geraschenko commented on Task1/Task1/TextProcessor.cs
> +        public static string getText(string path)
Имена методов принято называть в `PascalCase`

2020-08-31 12:25 UTC, alex-geraschenko commented on Task1/Task1/TextProcessor.cs
> +    class TextProcessor
Базовый класс должен быть абстрактным

2020-08-31 14:58 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-08-31 15:03 UTC, merged